const errors = {
    SUCCESS_PAYMENT: { code: 'SUCCESS_PAYMENT' },
    CAN_NOT_CREATE_PAYMENT: { code: 'CAN_NOT_CREATE_PAYMENT' },
    CAN_NOT_PAY_ORDER: { code: 'CAN_NOT_PAY_ORDER' },
    ACCOUNT_IS_NOT_ENOUGH_BALANCE: { code: 'ACCOUNT_IS_NOT_ENOUGH_BALANCE' },
    ACCOUNT_HAS_EXCEEDED_THE_DAILY_LIMIT: { code: 'ACCOUNT_HAS_EXCEEDED_THE_DAILY_LIMIT' },
    TRANSACTION_CANCELED: { code: 'TRANSACTION_CANCELED' },
    TRANSACTION_EXIST: { code: 'TRANSACTION_EXIST' },
    BANK_MAINTENANCE: { code: 'BANK_MAINTENANCE' },
    BANK_NOT_FOUND: { code: 'BANK_NOT_FOUND' },
    THIS_BANK_ACCOUNT_IS_NOT_YOURS: { code: 'THIS_BANK_ACCOUNT_IS_NOT_YOURS' },
    YOU_HAS_ADDED_BANK_ACCOUNT_FOR_THIS_BANK: { code: 'YOU_HAS_ADDED_BANK_ACCOUNT_FOR_THIS_BANK' },
    WRONG_OTP: { code: 'WRONG_OTP' },
    PLEASE_TRY_AGAIN_IN_A_MOMENT: { code: 'PLEASE_TRY_AGAIN_IN_A_MOMENT' },
    TRANSACTION_IS_SUSPICIOUS: { code: 'TRANSACTION_IS_SUSPICIOUS' },
    PAYMENT_NOT_FOUND: { code: 'PAYMENT_NOT_FOUND' },

}
export {
    errors
}